name: Scoop CheckVer

on:
  schedule:
  - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  checkver:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check versions
        run: |
          Invoke-WebRequest -Uri get.scoop.sh -OutFile scoop-install.ps1
          Invoke-Expression ".\scoop-install.ps1 -RunAsAdmin"
          $scoop_home = resolve-path (split-path (split-path (scoop which scoop)))
          $checkver = "$scoop_home/bin/checkver.ps1"
          $bucketdir = "$env:GITHUB_WORKSPACE"
          $output = Invoke-Expression "& '$checkver' -Dir '$bucketdir' -SkipUpdated *>&1"
          Write-Host $output
          if (${output} -ne $null) { exit 1 }
